### ISSUE TITLE
no viable alternative at input 'grant xxxxxx_role'  

### ISSUE THREAD

**Issue by luyomo** [luyomo/yomo-connector#2]
[2019-10-29 13:28:31,706] ERROR Unexpected exception while processing record 'ConsumerRecord(topic = test.hist, partition = 0, leaderEpoch = 0, offset = 336, CreateTime = 1572317612899, serialized key size = -1, serialized value size = 332, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = {
  "source" : {
    "server" : "test"
  },
  "position" : {
    "ts_sec" : 1572317655,
    "file" : null,
    "pos" : 8634197,
    "gtids" : "1-301-19285494,1303-303-45,18473-18457-680962",
    "server_id" : 303,
    "event" : 1
  },
  "databaseName" : "",
  "ddl" : "grant test_all_rw_role to test_user@'172.37.249.%'"
})' (io.debezium.relational.history.KafkaDatabaseHistory)
io.debezium.text.ParsingException: no viable alternative at input 'grant test_all_rw_role'
        at io.debezium.antlr.ParsingErrorListener.syntaxError(ParsingErrorListener.java:40)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1078)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:812)
        at io.debezium.connector.maria.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:68)
        at io.debezium.connector.maria.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:41)
        at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:80)
        at io.debezium.relational.history.AbstractDatabaseHistory.lambda$recover$1(AbstractDatabaseHistory.java:104)
        at io.debezium.relational.history.KafkaDatabaseHistory.recoverRecords(KafkaDatabaseHistory.java:240)
        at io.debezium.relational.history.AbstractDatabaseHistory.recover(AbstractDatabaseHistory.java:73)
        at io.debezium.connector.maria.MySqlSchema.loadHistory(MySqlSchema.java:252)
        at io.debezium.connector.maria.MySqlTaskContext.loadHistory(MySqlTaskContext.java:165)
        at io.debezium.connector.maria.MySqlConnectorTask.start(MySqlConnectorTask.java:107)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.antlr.v4.runtime.NoViableAltException
        at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:886)
        ... 19 more

**Comment by luyomo** [comment]
Add below error info

[2019-10-29 13:28:22,768] ERROR Unexpected exception while processing record 'ConsumerRecord(topic = test.hist, partition = 0, leaderEpoch = 0, offset = 336, CreateTime = 1572317612899, serialized key size = -1, serialized value size = 332, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = {
  "source" : {
    "server" : "test"
  },
  "position" : {
    "ts_sec" : 1572317655,
    "file" : null,
    "pos" : 8634197,
    "gtids" : "1-301-19285494,1303-303-45,18473-18457-680962",
    "server_id" : 303,
    "event" : 1
  },
  "databaseName" : "",
  "ddl" : "grant test_all_rw_role to test_user@'172.37.249.%'"
})' (io.debezium.relational.history.KafkaDatabaseHistory)

**Comment by luyomo** [comment]
grant role to user is not included in the parsing statement.

debezium/debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

**Comment by luyomo** [comment]
Skip the ddl parsing using the below config:
  , "database.history.skip.unparseable.ddl" : true

To avoid to miss any important query miss, need to monitor the below patten message.
[Ignoring unparseable DDL statement ] warning
